# Generated by Django 3.2.7 on 2021-10-14 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_dotd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
