# Generated by Django 3.2.7 on 2021-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pincode',
        ),
    ]
