# Generated by Django 3.2.7 on 2021-11-02 06:05

from django.db import migrations, models
import homepage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_homepagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=homepage.models.Blog.blog_image_upload)),
                ('heading', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
