# Generated by Django 3.2.4 on 2021-07-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210716_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
