# Generated by Django 3.2.4 on 2021-07-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210716_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sellingPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
