# Generated by Django 3.2.4 on 2021-07-18 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addedDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
