# Generated by Django 3.2.4 on 2021-08-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0008_productfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('address', models.CharField(max_length=1000)),
                ('contactNumber', models.IntegerField()),
                ('userId', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewedBy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
            preserve_default=False,
        ),
    ]
