# Generated by Django 3.2.4 on 2021-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='imageLink',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
