# Generated by Django 3.2.4 on 2021-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210805_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modelFile',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
