# Generated by Django 3.2.4 on 2021-08-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_modelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageLink',
            field=models.URLField(max_length=1000),
        ),
    ]
