# Generated by Django 3.2.4 on 2021-08-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_orderdetails_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='delivery_charges',
        ),
    ]
