# Generated by Django 3.2.4 on 2021-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_orderdetails_customer_delivery_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
