# Generated by Django 3.2.4 on 2021-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='newProduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(default='short description', max_length=2000),
            preserve_default=False,
        ),
    ]
