# Generated by Django 3.2.7 on 2021-09-22 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 6, 41, 43, 630017, tzinfo=utc)),
        ),
    ]
