# Generated by Django 3.2.7 on 2021-10-14 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('pin', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pincode'),
        ),
    ]
