# Generated by Django 3.2.7 on 2021-10-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('threshold', models.IntegerField(default=0)),
            ],
        ),
    ]
