# Generated by Django 3.2.7 on 2021-10-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
