# Generated by Django 3.2.7 on 2021-09-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartID',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='productId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='WishListID',
            new_name='wishlist',
        ),
    ]
