# Generated by Django 3.2.7 on 2021-10-10 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('bestSeller', models.BooleanField(default=False)),
                ('shortDescription', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=5000)),
                ('subcategory', models.CharField(max_length=100, null=True)),
                ('keyword', models.TextField(null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('model3d', models.FileField(blank=True, null=True, upload_to=products.models.model_upload)),
                ('addedDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewStar', models.FloatField()),
                ('reviewText', models.TextField(blank=True, null=True)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=100, null=True)),
                ('weight', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.image_upload)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=products.models.image_upload)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product')),
            ],
        ),
    ]
