# Generated by Django 3.2.7 on 2021-10-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='products.room'),
            preserve_default=False,
        ),
    ]
