# Generated by Django 3.2.7 on 2021-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
