# Generated by Django 3.2.7 on 2021-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
