# Generated by Django 3.2.7 on 2021-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_subcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='fullDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='newProduct',
            new_name='new',
        ),
        migrations.AddField(
            model_name='product',
            name='model3d',
            field=models.FileField(default='linkto3dmodel', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Model3D',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
