# Generated by Django 3.2.7 on 2021-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211014_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deliveryCondition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipsin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
