# Generated by Django 3.2.7 on 2021-09-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_image_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='model3d',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
