# Generated by Django 3.2.7 on 2021-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210921_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fullDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imageLink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='careInstruction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modelFile',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sellingPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model3d',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
