# Generated by Django 3.2.7 on 2021-09-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210922_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariationImage',
        ),
    ]
