# Generated by Django 3.2.7 on 2021-09-22 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_delete_productvariationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload),
        ),
        migrations.AlterField(
            model_name='product',
            name='model3d',
            field=models.FileField(blank=True, null=True, upload_to=products.models.model_upload),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
