# Generated by Django 3.2.7 on 2021-09-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_review_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
