# Generated by Django 3.2.7 on 2021-09-26 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dateAdded',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 9, 26, 6, 24, 47, 376811, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
