# Generated by Django 3.2.7 on 2021-09-26 12:33

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_review_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.image_upload),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
